//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Age { get; set; }
        public string Interests { get; set; }
        public int RaceId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Region Region { get; set; }
    }
}
